JosefNemec/Playnite

source/PlayniteUI/WindowPositionHandler.cs

Added logic to the main window position handler to resolve any first-load window positioning issues affecting users with smaller screen sizes than the defaults.

Fix: Window defaults to above screen #193

---

source/Playnite/Programs.cs

Improves automatic naming by looking at the version info from the file and getting the Product Name, this also leaves room for more improvement.

Fix: Improperly named games when importing from folder #171

---

source/Playnite/Providers/Steam/SteamLibrary.cs

Games synchronized with Steam now have News links on the left hand side of the details panel.
Relates to #227

Added news links to Steam synchronized games

---

source/Playnite/Providers/GOG/GogLibrary.cs
source/Playnite/Providers/GOG/WebApiClient.cs

Fix for #237. When a download for GOG metadata fails a `null` is returned from the GOG `WebApiClient.GetGameDetails` method. This `null` works its way up to `UpdateGameWithMetadata` as the `metadata.GameDetails` object. I've added a quick null check before that object is used. If `metadata.GameDetails` is null then the method logs a warning message and bails. 
I also ran a `Remove and Sort Usings` on the files.
Let me know if I need to improve anything, thanks!

Fix: Crashes when GOG metadata download fails

---

source/PlayniteUI/Localization/german.xaml

~~**:construction: This is work in progress, don't merge it yet!**~~
There are some untranslatable strings (testing with Playnite 4.1):
* "SDK Documentation" in main menu
* "Extensions -> Export Library" in main menu
* "Prefer game screenshot" option in settings window ("Steam" section) + its tooltip
* "Not Played" right after the "play time" input (not in the "game progress" dropdown, `LOCNotPlayed` is used just there and not for "play time")
* The `MetaSkipNonEmptyTooltip` language variable doesn't require a `LOC` prefix
* Fullscreen Mode: Sort by "Most played"
Some questions:
* The `LOCAdvanced`, `LOCScripts`, `LOCPlugins`, `LOCReloadScriptsSuccess` language variables don't seem to be used anywhere?
* Where are the `LOCCancelMonitoring*` language variables used? I'd assume they show up …

Update german localization

---

source/Plugins/SteamLibrary.Tests/SteamLibraryTests.cs
source/Plugins/SteamLibrary/GameExtension.cs
source/Plugins/SteamLibrary/ModInfo.cs
source/Plugins/SteamLibrary/Services/SteamServicesClient.cs
source/Plugins/SteamLibrary/Services/WebApiClient.cs
source/Plugins/SteamLibrary/Steam.cs
source/Plugins/SteamLibrary/SteamGameController.cs
source/Plugins/SteamLibrary/SteamLibrary.cs
source/Plugins/SteamLibrary/SteamLibrary.csproj
source/Plugins/SteamLibrary/SteamMetadataProvider.cs

As asked for in issue #769, this adds support for scanning/launching Source mods on Steam.
To do this, I had to change the Playnite Game ID to use a Steam Game ID instead of App ID, but there shouldn't be any backcompat issues since they have the same value for games that were already supported. (GameID is a 64-bit id, with the AppID as the lower 32 bits, and the high bits unset unless it's a mod or shortcut). There shouldn't be any effective change at all for non-mod games.
Metadata comes from the mod's gameinfo.txt, same as how Steam does it. For mods that have it populated, this provides the mod name, developer name, links (developer + manual), and categories (single-player, multi-player, or both). Icon can also be populated if Playnite can support tgas. (I couldn't find the icon image …

Add support for Source mods in Steam (issue #769)

---

source/Plugins/SteamLibrary/SteamLibrary.cs

In the SteamLibrary plugin, when querying the Steam GetOwnedGames web api directly, the include_played_free_games parameter isn't passed, so free games that have been played, such as Dota 2 or Team Fortress 2, will never be returned in the results.
PlayniteServices does pass this.

Include free games from Steam owned games API when not using PlayniteServices

---

source/Plugins/SteamLibrary/SteamMetadataProvider.cs

For some apps, Steam has the icon, clienticon, or logo fields defined in the appinfo, but with an empty value (""). This causes Playnite to try to download an image that will never exist, and throw an exception internally. App id 215, Source SDK Base 2006 is an example of this.
Ex. "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/215/.jpg"

Fix attempted fetching of non-existent Steam icons.

---

source/PlayniteUI/Converters/ListToStringConverter.cs
source/PlayniteUI/Skins/Classic/Classic.xaml
source/PlayniteUI/Skins/Modern/Modern.xaml

Fixed issue ( #782 ) where trailing space was deleted automatically preventing the entering of filters that contain whitespace (e.g. a Category named "To Be Completed")

Fixed accidental trimming of spaces put into filters

---

source/Plugins/SteamLibrary.Tests/SteamLibraryTests.cs
source/Plugins/SteamLibrary/SteamLibrary.cs

As discussed in #615, this adds support for importing "Hidden" status for Steam games during category import. (Categories and hidden status are stored very similarly in Steam).
This change also makes category/hidden import work for Steam mods.

Improve Steam category import (#615)

---

source/PlayniteUI/GamesEditor.cs

When the desktop is located on a different folder and/or drive, Playnite fails to create a shortcut. 
This fixes that by changing from an effectively hardcoded path to dynamically pulling the desktop path when creating a shortcut.

Create desktop shortcuts when desktop folder is not in default location.

---

source/Playnite/Emulators/Definitions.yaml

Allow playing Flash games in Playnite by using the Flash Player projector as an "emulator" for Adobe Flash. A new platform "Adobe Flash" is used for .swf files. Support for other Flash players could use this same platform.
I'm not too familiar with other Flash players, it may make sense to add some other players. Browsers don't really work, Chrome likes to download a local .swf file instead of opening it.
The only real issue with the Flash Player projector is that it has no built in full screen button, but some games have an internal button for that.

Add Flash Projector as an Adobe Flash emulator

---

source/PlayniteUI/Localization/italian.xaml

247    <sys:String x:Key="LOCSettingsSkinFullscreen">Fullscreen Theme</sys:String>
248    <sys:String x:Key="LOCSettingsSkinColorFullscreen">Fullscreen Theme Profile</sys:String>
Looks like the second line overrides the first line. In the English version the problem does not emerge, while, for example in Italian, there is an overlapping of text since the strings would be:
247  <sys:String x:Key="LOCSettingsSkinFullscreen">Tema Schermo Intero</sys:String>
248  <sys:String x:Key="LOCSettingsSkinColorFullscreen">Colore del tema Schermo Intero</sys:String>

Update italian.xaml and little problem

---

source/PlayniteUI/ViewModels/CategoryConfigViewModel.cs
source/PlayniteUI/Windows/CategoryConfigWindow.xaml
source/PlayniteUI/Windows/GameEditWindow.xaml

Game edit window changes:
* Set default button in `GameEditWindow` to `ButtonOK`
Category config window changes:
*  Conditionally set default button in `CategoryConfigWindow`. If `NewTestCat` is not focused, use `ButtonOK` as default. If   `NewTestCat` is not focused, use `ButtonAddCat` as default.
*  Clear `NewTestCat` on `AddCategory()`. I had to add a property for   `NewTextCat` in `CategoryConfigViewModel` to do this, I'm not sure   if that's the cleanest way.
*  Don't add the `Category` to `Categories` if it already exists and is   enabled. This fixes a bug that you could have duplicate categories   listed.
*  If the category does already exist but is not enabled, enable it. I   had to make `Category` an `ObservableObject` for this to work, it   needed to be able to notify that it …

Improve UI interactions in game edit and category windows

---

scripts/Extensions/ScummVMImporter/ScummVMImporter.ps1
scripts/Extensions/ScummVMImporter/extension.yaml

The `State` property no longer exists on Game objects as of 3371c606. Change the extension to use the new `IsInstalled` setter.

Update ScummVMImporter to use the refactored Game api

---

source/Playnite/Settings/PlayniteSettings.cs
source/PlayniteUI/Controls/GamesGridView.xaml
source/PlayniteUI/Localization/english.xaml
source/PlayniteUI/Localization/french.xaml
source/PlayniteUI/Skins/Classic/Classic.xaml
source/PlayniteUI/Skins/Modern/Modern.xaml
source/PlayniteUI/Windows/SettingsWindow.xaml

This is a PR for the issue #989 . It adds an option in the appearance settings to show the item count next to the group name in list or grid view.
This is my first time contributing on github and my first time working in .net (I usually work in java). I'm sorry if I made stupid mistakes.
I was not sure from what branch to branch from. At first I tried with devel but I could not get the application running (xaml parsing error) so I branched from master.
Also, I added a new language string in English and French. I'm not sure what to do with the other languages.
Thanks
JF

Add option to show grouped items count (#989)

---

source/Plugins/SteamLibrary/Services/WebApiClient.cs
source/Plugins/SteamLibrary/Steam.cs
source/Plugins/SteamLibrary/SteamMetadataProvider.cs

Most or all of these links already get redirected to HTTPS. This way we're saving that step. ~~Also fixed forum link going to hub instead of discussion forum.~~ (see comments)

Use HTTPS for Steam links.

---

source/Playnite.DesktopApp/DesktopApplication.cs
source/Playnite/App/PlayniteApplication.cs
source/Playnite/Localization/LocSource.xaml
source/Playnite/Playnite.csproj
source/Playnite/ViewModels/UpdateViewModel.cs
source/Playnite/WindowsNotifyIconManager.cs

Fixes #995 
So while working on this, I've noticed a minor annoyance with `NotifyIcon`, and that's if you don't `Dispose()` of it, the notification icon stays in the tray bar forever (or until you close Playnite). However, once I've hooked `Dispose()` to the notification close event, it would not stay in the W10 notification bar after a couple of seconds (so the notification would be utterly pointless while the person is let's say gaming in the background)
Therefore I've tried delving a little into `ToastNotification`, but quickly realized utilizing the API while the project doesn't target W10 specifically or is not a UWP app; becomes a real pain in the ass.
Finally, while traversing through the project, I've noticed that the `TaskBarIcon` class utilized for the tray operations of …

Rework background update notifications (devel rebase)

---

source/Playnite/Localization/LocSource.xaml
source/Plugins/SteamLibrary.Tests/SteamLibraryTests.cs
source/Plugins/SteamLibrary/SteamLibrary.cs
source/Plugins/SteamLibrary/SteamLibrarySettings.cs
source/Plugins/SteamLibrary/SteamLibrarySettingsView.xaml

LastActivity data is imported from \steam\userdata\{steam_id}\config\localconfig.vdf
A button has been added to `SteamLibrarySettings` to trigger import. Updating a game's `LastActivity` if it skipped if is Playnite's value is newer than Steam's data.
I named things "LastActivity" throughout the code even though the Steam and the Playnite UI says "Last Played" usually. It seemed to match the code better, let me know if it's confusing.
I'm not sure if I have any Steam mods in my account, I couldn't test whether `localconfig.vdf` has underscores in AppIds like `sharedconfig.vdf`.
I added a `GetGamesLastActivityTest()`,  but I don't know how to actually get tests to run in Visual Studio. Could you please help?
I introduced multiple new localization strings. I added them to `english.xaml`, …

Import LastPlayed information from Steam

---

source/Plugins/SteamLibrary/SteamMetadataProvider.cs

Adds a converter to automatically replace %CDN_HOST_MEDIA_SSL% with
steamcdn-a.akamaihd.net.
Affects Hollow Knight metadata import.
Fixes #1205.
Screenshot after fix:

Replaces %CDN_HOST_MEDIA_SSL% for Steam games

---

source/Playnite.Common/Programs.cs
source/Playnite.DesktopApp/ProgramEntry.cs
source/Playnite.FullscreenApp/ProgramEntry.cs
source/Playnite/App/CmdLineOptions.cs
source/Playnite/Settings/PlayniteSettings.cs

For #1285 
Added a new startup argument named 'hidesplashscreen' which suppresses the splash screen when Playnite starts.  This parameter is added to the Playnite.lnk file which is generated when a user selects to start Playnite at windows startup (via Options...), thereby preventing the splash screen from appearing at Windows startup but retains the splash screen if Playnite is started manually.

Suppress splash screen when Playnite starts at Windows startup

---

source/Plugins/SteamLibrary/SteamMetadataProvider.cs

Proposed changes
`Forums` -> `Community Hub`
`Discussions` (I added this one)
`Store` -> `Store Page`
`Wiki` -> `PCGamingWiki`

Term Changes to Steam links and one more added

---

source/Plugins/SteamLibrary/Steam.cs
source/Plugins/SteamLibrary/SteamMetadataProvider.cs

The link opens in the Steam client, that way there won't be problems in case you are not logged in on Steam in the web browser. I figured this can be a solution until there's native achievement support in Playnite

Add Achievement links to Steam Games

---

build/common.ps1

- Prefer VS2017 when present
- Fall back to VS2019
- Improved error handling when no suitable MSBuild is present

Allow MSBuild from VS2019

---

source/Playnite/Localization/LocSource.xaml

I propose modifying three strings to be more clear:
1. `Force sync play time` -> `Force sync Play Time for supported libraries` (Makes it clear that not every library is supported)
2. `Always download recorded play time from remote library during library sync, ignoring time recorded by Playnite.` -> 
`Always download recorded Play Time from remote library during library sync, ignoring time recorded by Playnite. GOG, Origin and Steam libraries are supported when the user is authenticated.` (To specify exactly what libraries are supported and to explain that the user must be currently authenticated in each respective library for Playtime Sync to work.
3. `Playtime is tracked and stored in seconds.` -> `Play Time is tracked and stored in seconds.` (For consistency since the other strings …

Modify Loc Strings related to playtime sync

---

source/Playnite.DesktopApp/Windows/CrashHandlerWindow.xaml
source/Playnite/Diagnostic.cs
source/Playnite/Localization/LocSource.xaml
source/Playnite/ViewModels/CrashHandlerViewModel.cs

#1349 
This PR adds the option for the user to provide additional information about steps taken before a crash occurred. This description is then added as a text file to the diagnostic package.
There is another CrashWindow in the FullscreenApp project. Is that still work in progress? Should I add the textbox there as well?

#1349 - Option to add description to crash dialog

---

source/Playnite/Emulators/Definitions.yaml

And small fix to the bsnes-hd profile.

Separate Bizhawk and Mednafen emulator profile by platforms in emulator definitions file and standarize some platform names

---

source/Playnite.DesktopApp/ViewModels/GameEditViewModel.cs

I've found that changing artwork to wallpaper in background images search for google images gets better results due to the following:
- Searching with artwork gives images with very diverse aspect ratios and resolutions
- Searching with wallpaper gives mostly images with widescreen aspect ratio and generally higher resolutions

Change "artwork" to "wallpaper" for google images for better results

---

source/Playnite.DesktopApp/ViewModels/DesktopAppViewModel.cs
source/Playnite.DesktopApp/Windows/MainWindow.xaml

For #1704
I think it makes more sense to use `ctrl+e` for the explorer panel, since the emulator import wizard is rarely used. I changed that one to `ctrl+q`, that way the key combination will be next to the library manager.

Add Explorer panel Keyboard Shortcut for #1704

---

source/Playnite.DesktopApp/Controls/GameMenu.cs
source/Playnite.DesktopApp/ViewModels/DesktopAppViewModel.cs
source/Playnite/GamesEditor.cs
source/Playnite/Localization/LocSource.xaml
source/Playnite/Localization/de_DE.xaml

Since this is my first contribution I wanted to make sure I can get everything to work before making promises on the ticket. So sorry for the "surprise" pull request.
As proposed in https://github.com/JosefNemec/Playnite/issues/1796 I added an item in the game context menu to change the completion status:
If this change is welcome I'd also make a similar change to the version of the context menu that handles multiple selected games.
Obviously the Header should be "Set Completion Status", but I don't know the process for updating the localizations so I reused the existing string.

add submenu for changing completion status to game context menu (#1796)

---

source/PlayniteServices/Controllers/Steam/LibraryController.cs
source/Plugins/SteamLibrary/SteamLibrary.cs

Recreating #1778 against devel8 per https://github.com/JosefNemec/Playnite/pull/1778#issuecomment-647020228
> Earlier this week, Steam added a new parameter to their IPlayerService/GetOwnedGames Web API call to opt into including free games that everyone owns. By adding this, more uninstalled games can be synced.
>
> In testing, it does pull at least some more for me.
>
> See: SteamDatabase/SteamTracking@e84ef2b#diff-1dd8848646dd2385514346656345b4d4R90 or https://api.steampowered.com/ISteamWebAPIUtil/GetSupportedAPIList/v1?key=KEYHERE

Add new include_free_sub parameter for Steam GetOwnedGames API call.

---

source/Plugins/SteamLibrary/SteamGameController.cs

Look up install folder of base game when launching a mod, using that in place of the mod's own install directory for the process watcher. Fixes #1936. Tested with a regular Steam game, a GoldSrc mod, and a Source mod.

Use base game install folder with process watch for Steam mods (fixes #1936)

---

source/Playnite/Resources/DescriptionView.html

Makes images in description fit description size by modifying the default "img" style

Makes images in description fit description size

---

source/Playnite/GamesEditor.cs
source/Playnite/Scripting/PowerShell/PowerShell.cs
source/Playnite/Scripting/PowerShell/PowerShellScript.cs
source/Tests/Playnite.Tests/Scripting/PowerShell/PowerShellTests.cs

Add names to PowerShell runspaces for easier debugging.
Example usage:
```
PS C:\Users\Blake\Code\playnite\Playnite> Enter-PSHostProcess -Name Playnite.DesktopApp
[Process:19948]: PS C:\Users\Blake\Documents> Get-Runspace
Id Name            ComputerName    Type          State         Availability
-- ----            ------------    ----          -----         ------------
1 LibraryExpor... localhost       Local         Opened        Available
3 RemoteHost      localhost       Local         Opened        Busy
4 Inline scrip... localhost       Local         Opened        Busy
[Process:19948]: PS C:\Users\Blake\Documents> (Get-Runspace).Name
LibraryExporter.ps1
RemoteHost
Inline script: EnterTheGungeon
[Process:19948]: PS C:\Users\Blake\Documents> Debug-Runspace -Name "LibraryExporter.ps1" …
```

Added names to PowerShell runspaces for easier debugging

---

source/Playnite.DesktopApp/Resources/contributors.txt
source/Playnite.DesktopApp/ViewModels/InstalledGamesViewModel.cs

addressing #2215 
import single files similarly to how a whole folder is imported. Addtionally enables to import single .lnk files pointing to .exe or .bat files, or .bat files themselves.
Also: for .lnk files the file name of the shortcut is used as the game name, if it is not empty.

Improved single file import in InstalledGamesView for .lnk files

---

source/Playnite/Database/GameDatabase.cs

Fix: Prevent updating game library entries during library update when no data has changed. Fixes #2384

Fix: Prevent updating game library entries during library update when no data has changed. Fixes #2384

---

source/Playnite.DesktopApp/ViewModels/GoogleImageDownloadViewModel.cs
source/Playnite.DesktopApp/Windows/GoogleImageDownloadWindow.xaml
source/Playnite/Localization/LocSource.xaml

Fixes #1674
Added presets for background images for now. The `Any` option clears the text boxes

 New: Support to search for specific resolutions during google image searches and added resolution presets. Fixes #1674

---

source/Playnite/Audio.cs

Currently the volume settings behave weirdly because it's volume is linear. The volume should be calculated with a logarithm
Some resources:
- https://www.dr-lex.be/info-stuff/volumecontrols.html
- https://www.reddit.com/r/programming/comments/9n2y0/stop_making_linear_volume_controls/
There's some debate but the proposed and simple solutions is to calculate the volume with `x4` and `x2` respectively. 
I tested both solutions and found `x2` to sound more natural. Notice how the volume growth sounds very unnatural in the lower values in the linear function.
Current (Linear):
https://user-images.githubusercontent.com/1389286/131268349-c9ff1f23-d0e2-4c00-a22f-66757c52f523.mp4
Proposed (`x2`):
https://user-images.githubusercontent.com/1389286/131268359-37b89e1e-7674-41f4-997d-020445e91f5d.mp4 …

Fix: audio playback using linear Volume

---

source/Playnite.DesktopApp/ViewModels/GameEditViewModel.cs
source/Playnite/Localization/LocSource.xaml
source/Playnite/Localization/LocalizationKeys.cs

Fixes:
- Allow drag and drop of all compatible extensions listed in the file selection dialog. Fixes #1679
- Show an error dialog if a file with an incompatible extension is dragged
- Small refactor to prevent duplicate code in several methods
- Added the performance check in methods missing them for consistency

Fix: Game Edit media drag and drop fixes

---

source/Playnite/Converters/ListToStringConverter.cs

Added custom seperator string to ListToString converter using the parameter object

ListToStringConverter seperator as parameter

---

source/Playnite/GamesEditor.cs

Fix Auto-close client executing even if another game from the same library is running
Fixes https://github.com/JosefNemec/Playnite/issues/2635

Fix Auto-close client executing even if another game from the same library is running

---

source/Playnite/Emulation/Emulators/RetroArch/emulator.yaml

Adds a profile for https://github.com/libretro/swanstation

Add SwanStation profile for RetroArch

---

source/Playnite/Plugins/ExtensionFactory.cs

Assembly.GetTypes() can throw a ReflectionTypeLoadException which
contains all exceptions thrown by the class loader in the
LoaderExceptions property.
Resolves #2758

Log all exceptions when loading Plugins

---

source/Playnite.DesktopApp/Controls/NumericDoubleBox.cs
source/Playnite.DesktopApp/Resources/contributors.txt

This fixes #2789 by converting both possible separator characters to the one used by the user's current culture.
This is a somewhat naive solution, because it basically only extends the previous behavior to work for all cultures, which means it won't work for numbers that also contain a thousands separator.
This is probably not going to be an issue, but let me know if you would prefer a more accurate solution, which will require the user to use the correct decimal separator.

Parse doubles according to user culture

---

source/Playnite.DesktopApp/ViewModels/DesktopAppViewModel.cs

Currently the details for the Random Game Picker always open the details in DetailsView. With this PR, the view change is only done if the current view is ListView, which can't display the game details. If the current view is GridView then the view is not switched and the game details will be displayed there.

Open details on GridView for Random Game Picker if active view

---

source/Playnite.DesktopApp/Themes/Desktop/Default/Views/SearchView.xaml

I think that the game platform(s) is very important data to know when viewing a game. It can also help in cases where multiple games share the same name and the only way to distinguish them is the platform.
Screenshot:

Add platforms to SearchView GameItem subtext

---

source/Playnite.DesktopApp/GlobalResources.xaml
source/Playnite.FullscreenApp/GlobalResources.xaml
source/Playnite/Converters/StringToUpperCaseConverter.cs
source/Playnite/Playnite.csproj

Some notes:
- I used `ToUpperInvariant()` method to make sure the converted value is consistent in all systems
- To use the converter with localization strings, they must be used as StaticResource in the binding, for example:
```xml
<TextBlock Text="{Binding Source={StaticResource LOCGameDescriptionTitle}, Converter={StaticResource StringToUpperCaseConverter}}" />
```

Add StringToUpperCaseConverter

---

source/Playnite/GamesEditor.cs

Update game LastActivity, PlayCount and Completion Status on Runningstate instead of Launching
I think it makes more sense to update those values when the game has started running, as it's not guaranteed that the game will run when the game is still in `Launching` state

Update game LastActivity, PlayCount and Completion Status on Running

---

source/Playnite.DesktopApp/Themes/Desktop/Default/Views/DetailsViewGameOverview.xaml
source/Playnite.DesktopApp/Themes/Desktop/Default/Views/GridViewGameOverview.xaml

From https://github.com/JosefNemec/Playnite/commit/0ca9176b09fb6768e9025356fa0e66411d53e64d
It seems I overlooked increasing the GridEx RowCount for the new elements in details...

Fix incorrect GridEx RowCount in details views

---

source/Playnite.DesktopApp/Controls/Views/FilterPanel.cs
source/Playnite.DesktopApp/DesktopCollectionView.cs
source/Playnite.FullscreenApp/Controls/Views/FiltersAdditional.cs
source/Playnite.FullscreenApp/ViewModels/FullscreenAppViewModel_Commands.cs
source/Playnite/Database/DatabaseExplorer.cs
source/Playnite/GamesCollectionView.cs
source/Playnite/GamesCollectionViewEntry.cs
source/Playnite/Localization/LocalizationKeys.cs
source/Playnite/Settings/FilterSettings.cs
source/PlayniteSDK/Models/FilterPreset.cs
source/PlayniteSDK/Models/Game.cs

- Filter support in Filter and Explorer Panels and for Fullscreen Mode for `InstallSize` property (Closes https://github.com/JosefNemec/Playnite/issues/3075)
- Filter support in Filter and Explorer Panels and for Fullscreen Mode for `RecentActivity` property (Closes https://github.com/JosefNemec/Playnite/issues/3075)
- Grouping support for `RecentActivity` property. (Closes https://github.com/JosefNemec/Playnite/issues/3076)

Add support to filter by InstallSize and RecentActivity. Group by RecentActivity

---

source/Playnite/Localization/LocSource.xaml
source/Playnite/Localization/LocalizationKeys.cs
source/Playnite/ViewModels/MainViewModelBase.cs

Scans size of game of imported by scanners during library update
Note: Doesn't include scan for games on MainMenu -> Added. That's for another PR...

Scan install size when updating emulation libraries

---

doc/tutorials/themes/installing.md

This info for setting your active theme should really/also be on the "How to: Themes" page but I couldn't figure out how to edit that. 
https://github.com/JosefNemec/Playnite/wiki/How-to:-Themes
Info on how to change your active/applied theme isn't available anywhere that I could find. I could only find a reddit post with someone else asking the same question. We both assumed you could toggle a theme active in the Addons>Installed>Themes window (like how Firefox etc does it). _[That would also be a nice addition to the program.]_ 
My next guess was that in the main dropdown menu there was a Theme submenu, or View>Theme or Add-ons>Theme or Extensions>Theme or something where I could select my active theme. I was wrong again so I had to look through help docs and then just do an internet …

Add info for switching active theme

---

source/Playnite.DesktopApp/Controls/Menus/MainMenu.cs
source/Playnite.FullscreenApp/Themes/Fullscreen/Default/Views/HelpMenu.xaml
source/Playnite.FullscreenApp/ViewModels/HelpMenuViewModel.cs
source/Playnite.FullscreenApp/Windows/HelpMenuWindow.xaml
source/Playnite/ViewModels/MainViewModelBase.cs

Helps in these cases:
- Addons were updated but user didn't restart when prompted. Currently you have to manually close and open the app again.
- Until https://github.com/JosefNemec/Playnite/issues/1903 is done, there's no easy way to restart if a setting in a plugin requires it but even then, the previous point would apply in this case
- Current UI framework has issues has several issues related to DPI (E.g. https://github.com/JosefNemec/Playnite/issues/2719) , one of them being that Playnite won't properly render to the new DPI when moving it to another screen which results in general blurriness and currently the only way to fix this is by restarting the app so it properly renders in the target screen setup. This is nothing but a workaround but I think it could be …

Add main menu buttons to restart Playnite

---

source/Playnite/Database/GameDatabase.cs

Current behavior: Only updates LastActivity if
- Existing game LastActivity is null
New behavior: Updates LastActivity if:
- Existing game LastActivity is null
- New game LastActivity is newer

Fix LastActivity not being updated to existing game on library update

---

source/Playnite/GamesEditor.cs
source/Playnite/Localization/LocSource.xaml

**Description**
Shows the game name in the confirmation dialog before it is removed. This addresses https://github.com/JosefNemec/Playnite/issues/2983
**Testing Performed**
Tested with a steam game and an emulator game (they use different strings)

Show game name in the confirmation dialog before removing game

---

source/Playnite/Emulation/Emulators/ScummVM/importGames.ps1

Two changes:
1) Search for scummvm.ini in the scan directory first, then search appdata if not found.
2) Updated the $rompath construction to support relative paths in the scummvm.ini file. $anyFunc also had to be updated to properly identify games already imported using relative paths.
**Code contributions (pull requests) are currently not being accepted while majority of code base is being rewritten for Playnite 11.**
**Please wait with any pull requests after P11 is at least in beta state.**

Update importGames.ps1 to support portable install and relative path

---

source/Playnite/Emulation/Emulators/shadPS4/emulator.yaml
source/Playnite/Emulation/Emulators/shadPS4/importGames.ps1
source/Playnite/Emulation/Platforms.yaml

- Added shadPS4 emulator definition
- Added modified version of RPCS3 import script to support PS4 games

Added shadPS4 emulator support (by vaughngx4) #3897

---

source/Playnite/Emulation/Emulators/jgenesis/emulator.yaml
source/Playnite/Emulation/Platforms.yaml

Just as a note in case you are wondering why some profiles share the same hardware in command line, it's not an error and it's because they use the same hardware internally in the emulator. Profiles are defined per system, and follows the command line systems:
- https://github.com/jsgroth/jgenesis/blob/d16262b57d37b5c9ff70134c9e3a77166661dd78/frontend/jgenesis-native-driver/src/extensions.rs#L12-L20
- https://github.com/jsgroth/jgenesis/blob/d16262b57d37b5c9ff70134c9e3a77166661dd78/frontend/jgenesis-cli/src/main.rs#L29-L37

Create jgenesis emulator profile

---

source/Playnite/Common.config

Although Playnite correctly creates its named pipe with a unique base address (`net.pipe://localhost/PlaynitePipe`) along with an additional identifier (`PipeEndpoint`), some "misbehaving" programs may interfere when they use only `net.pipe://localhost` as their base address, even if these programs append a unique segment in the `AddServiceEndpoint` call, they can end up intercepting Playnite's calls.
This issue can lead to "Startup Error"s, displaying the message "Playnite failed to start. Please close all other instances and try again.", in some scenarios, like when launching a game from a Playnite desktop shortcut while Playnite is already running.
To avoid this, I added the configuration `wcf:useBestMatchNamedPipeUri`, which instructs the .NET Framework to select the "best matching" …

Avoid named pipe conflicts
