README.md
Changed "Steam" to "SteamKey" as per [LibraryController implementation](https://github.com/JosefNemec/Playnite/blob/master/source/PlayniteServices/Controllers/Steam/LibraryController.cs#L30)
=> Updated developer documentation

source/PlayniteUI/Localization/german.xaml
~~This is still 🚧 **Work In Progress**.~~ Help is highly appreciated (simply leave a comment down below)!
* General
* Windows & Wizards
* Games
* Misc.
=> Add German localization

source/PlayniteUI/Localization/german.xaml
=> Update german localization

source/Playnite/Emulators/Definitions.yaml
Added several profiles to make easier game import when emulator supports more systems.
=> New profiles in Definitions.yaml

source/PlayniteUI/Localization/french.xaml
I saw some horrible things in the french translation, so I fixed them. It's not adding a new language, but fixing one, so..
=> Better french translation

source/Playnite/Emulators/Definitions.yaml
* ZX Spectrum platform added to Bizhawk
* LHA extension added to Amiga emulators
=> Vita3K profile added

source/PlayniteUI/Localization/spanish.xaml
=> Update spanish.xaml on master

source/Playnite/Emulators/Definitions.yaml
=> Added definition for D-Fend Reloaded

scripts/Extensions/import_games_from_file.py
Perhaps in the future, I can add support for CSV/JSON/YML key-value pairs to add properties to each game if people actually find this useful.
=> Add example of Python extension

source/Playnite/Emulators/Definitions.yaml
SNK Neo Geo CD platform added for MAME, new extensions for yuzu.
=>  Update Definitions.yaml

README.md
There were a couple of things that were bugging me about the readme, so I made a few improvements.
=> Readme english + fact corrections

source/PlayniteUI/Localization/brazilian.xaml
=> Update brazilian.xaml for 4.70

source/Playnite/Settings/ViewProperties.cs, source/PlayniteUI/Controls/SliderWithPopup.xaml, source/PlayniteUI/Controls/SliderWithPopup.xaml.cs, source/PlayniteUI/Converters/CoversZoomToPercentageConverter.cs, source/PlayniteUI/Playnite.UI.csproj, source/PlayniteUI/Skins/Classic/Classic.xaml, source/PlayniteUI/Skins/Modern/Modern.xaml
Implementation of the proposal specified in #899.
Took me a while to figure this one out due to my unfamiliarity with WPF, but this should do.
=> Add percentage popup to the zoom slider upon MouseOver

source/Plugins/EpicLibrary/EpicLibrary.cs
Fixes #1009 (but probably only for future game imports)
=> Fix Source not being set for games from Epic Games Launcher.

source/PlayniteUI/CollectionView/CategoryView.cs, source/PlayniteUI/Localization/english.xaml
Resolution of #570, haven't even bothered asking since the issue is so old and has a fairly simple solution.
=> Add LOC String for "No Category"

source/Plugins/ItchioLibrary/ItchioLibrary.cs
Currently the source property isn't set on itch.io games.
=> Set source on itch.io games

source/PlayniteUI/ViewModels/FullscreenViewModel.cs
=> Added sort option "Recently added" to fullscreen view

build/build.ps1
=> Support building with VS2017 Enterprise (#1036)

build/build.ps1, build/buildSdkNuget.ps1
=> Don't download NuGet if it's already in the PATH (#1038)

source/PlayniteServices/Models/IGDB/IGDB.cs
Hello Josef,
Here is the pull request as we discussed on Discord,
Cheers!
Angelo
=> Potential fix to bug: wrong label on Reddit link

source/PlayniteServices/Controllers/IGDB/GamesController.cs, source/PlayniteServices/Controllers/Steam/AppInfoController.cs, source/PlayniteServices/Controllers/Steam/StoreController.cs, source/PlayniteServices/PlayniteServices.csproj, source/Tools/DbTools/DbTools.csproj, source/Tools/PlayniteInstaller/PlayniteInstaller.csproj, source/Tools/PlayniteInstaller/ViewModels/MainViewModel.cs
Was trying to do some work on #1085 but couldn't even run the program properly up until force removal of the `packages`, `bin` and `obj` folders, cleanup of the `.suo` file and a couple of VS restarts, then I hit these barriers.
=> Fix devel build issues

source/Playnite/WebView/WebView.cs
=> Show web page title in Web View Window titles #1213

source/Plugins/OriginLibrary/Models/GameStoreDataResponse.cs, source/Plugins/OriginLibrary/Models/UsageReponse.cs, source/Plugins/OriginLibrary/OriginLibrary.cs, source/Plugins/OriginLibrary/OriginLibrary.csproj, source/Plugins/OriginLibrary/Services/OriginAccountClient.cs
=> Sync PlayTime and LastPlayed from Origin #1140

source/Playnite.FullscreenApp/Controls/Views/Main.cs, source/Playnite.FullscreenApp/ViewModels/FullscreenAppViewModel.cs
=> F11 switches from Fullscreen to Desktop

source/Playnite.DesktopApp/Resources/contributors.txt, source/PlayniteSDK/Models/PlaytimeCategory.cs
=> Use LOCPlayedNone localized string

source/Playnite.Common/Extensions/BitmapExtensions.cs
=> ignore color profile

source/Playnite.DesktopApp/ViewModels/DesktopAppViewModel.cs, source/Playnite.DesktopApp/Windows/MainWindow.xaml, source/Playnite.FullscreenApp/Controls/Views/Main.cs, source/Playnite.FullscreenApp/ViewModels/FullscreenAppViewModel.cs
For #1547, I used the F6 key for the PR. Targeting the `Devel` branch since I see you moved work to this one for the Playnite 7 release.
=> Keyboard Shortcut to use Random game picker

source/Playnite.DesktopApp/Resources/contributors.txt, source/Plugins/HumbleLibrary/HumbleLibrary.cs
Closes #1797 when completed, but not ready to merge yet, which is why it's a draft.
=> Update logic for checking if Humble games have keys for another service

source/Playnite.DesktopApp/Resources/contributors.txt, source/Playnite.DesktopApp/ViewModels/GameEditViewModel.cs, source/PlayniteSDK/Plugins/MetadataPlugin.cs
=> OnDemandMetadataProvider can now provide more fields

source/Playnite/Localization/LocSource.xaml, source/Plugins/SteamLibrary/SteamShared/MetadataProvider.cs
=> Add Steam guides link

source/Playnite/Emulators/DuckStation.yaml
=> Add DuckStation emulator profile

source/Playnite/Emulators/NanoboyAdvance.yaml
=> Add NanoboyAdvance emulator profile

source/Playnite/Emulators/Dolphin.yaml
=> Add rvz and wia extension to Dolphin emulator profile

source/Playnite.DesktopApp/Resources/contributors.txt, source/Playnite/Emulators/Xenia.yaml
Modify regex to also look at Xenia canary binary.
=> Add xenia canary support

source/Playnite.DesktopApp/Controls/SettingsSections/AppearanceGridView.xaml, source/Playnite/Localization/LocSource.xaml
=> Add square aspect ratio preset to grid view settings

source/Playnite/Emulators/FBNeo.yaml, source/Playnite/Emulators/FightCade.yaml, source/Playnite/Emulators/Flycast.yaml
- [Yes] These changes work, by building the application and testing them.
- [Yes] Pull request is targeting `devel` branch.
- [No] I added myself into [contributors file](https://github.com/JosefNemec/Playnite/blob/devel/source/Playnite.DesktopApp/Resources/contributors.txt) if I want to receive contribution credit in the application itself.
Sorry about that. Added support for Flycast and FBNeo, as well as updating the Fightcade handler.
=> Take 2: Added emulators.

source/Playnite/Emulation/Regions.yaml
=> Add more regions specifications

source/Plugins/GogLibrary/GogLibrary.cs
=> New: GOG playtime import support

source/Playnite.DesktopApp/Windows/ItemSelectionWithSearchWindow.xaml
=> Fix: Remove background for search area in ItemSelectionWithSearchWindow

source/Playnite.DesktopApp/Controls/SettingsSections/AppearanceTopPanel.xaml, source/Playnite.DesktopApp/Controls/Views/TopPanel.cs, source/Playnite.DesktopApp/Themes/Desktop/Default/Views/TopPanel.xaml, source/Playnite/Localization/LocSource.xaml, source/Playnite/Localization/LocalizationKeys.cs, source/Playnite/Settings/PlayniteSettings.cs
=> New: Option to show button to open Random game picker on Top panel

source/Playnite.DesktopApp/ViewModels/MetadataComparisonViewModel.cs, source/Playnite.DesktopApp/Windows/MetadataComparisonWindow.xaml
=> New: Show images dimensions in metadata comparison window  Fixes #2364

source/Playnite.DesktopApp/Resources/contributors.txt, source/Playnite/Emulation/Emulators/RetroArch/emulator.yaml
=> Support auto-detecting Genesis Plus GX Wide

source/Playnite.DesktopApp/Resources/contributors.txt, source/Playnite/Emulation/Emulators/RPCS3/importGames.ps1
=> Rpcs3 game scan improvement

source/Playnite/GamesCollectionView.cs
Fix "AND" style filtering not working correctly for games marked as favorite
=> Fix "AND" style filtering not working correctly for games marked as favorite

source/PlayniteSDK/ILogger.cs
There were some small typos in ILogger's descriptions.
=> Fixed ILogger's typos

source/Playnite/GamesCollectionView.cs, source/Playnite/Settings/FilterSettings.cs
=> Added filter textbox use when "Match all filters" is checked

source/Playnite.DesktopApp/ViewModels/GameDetailsViewModel.cs, source/Playnite.FullscreenApp/ViewModels/GameDetailsViewModel.cs, source/Playnite/GamesCollectionViewEntry.cs
=> Fix typo in 'IsUninstalling' property name

.github/ISSUE_TEMPLATE/bug_report.yml, .github/ISSUE_TEMPLATE/feature_request.yml
https://github.com/darklinkpower/Playnite/blob/master/.github/ISSUE_TEMPLATE/feature_request.yml
https://github.com/darklinkpower/Playnite/blob/master/.github/ISSUE_TEMPLATE/bug_report.yml
=> Update issues template to use checkboxes

.github/ISSUE_TEMPLATE/bug_report.yml, .github/ISSUE_TEMPLATE/feature_request.yml
=> Rever issues checkboxes

source/Playnite/Common/Programs.cs, source/Playnite/Common/Programs2.cs, source/Tests/Playnite.Tests/ProgramsTests.cs
=> Ignore config, redistributables and game engine executables during executables scan #2919

source/Playnite/ViewModels/SearchViewModel.cs
=> Open details on GridView for SearchView if active view

doc/tutorials/extensions/vscodeWindows.md, doc/tutorials/toc.yml
=> tutorial: C# extension using vscode in windows

source/Playnite/GamesCollectionView.cs
=> Made Version field filter case insensitive

source/Playnite/Emulation/Emulators/RosaliesMupenGui/emulator.yaml, source/Playnite/Emulation/Platforms.yaml
=> Add Rosalie's Mupen GUI emulator profile

source/Playnite/Emulation/Emulators/simple64/emulator.yaml, source/Playnite/Emulation/Platforms.yaml
Adds simple64 emulator profile: https://simple64.github.io/
I've tested the changes and the emulator is importing correctly:
But I'm getting this error when trying to launch any emulated game with any emulator (Not only with this one):
```
05-09 21:30:46.397|INFO |GamesEditor:Starting 007 - GoldenEye, 4de7b4cd-e1d3-4465-9f0c-5f9fca4f1c2e, 3aec0ac5-930e-4bca-9a34-a8f2b2a879ed, 00000000-0000-0000-0000-000000000000
05-09 21:30:46.429|DEBUG|GamesEditor:Using generic controller to start emulated game.
05-09 21:30:46.429|ERROR|GamesEditor:Cannot start game: 
Newtonsoft.Json.JsonSerializationException: Could not create an instance of type Playnite.SDK.Models.EmulatorProfile. Type is an interface or abstract class and cannot be instantiated. Path 'BuiltInProfileName', line …
```
=> Add simple64 emulator profile

source/Playnite.DesktopApp/Controls/SettingsSections/AppearanceTopPanel.xaml, source/Playnite.DesktopApp/Controls/Views/TopPanel.cs, source/Playnite.DesktopApp/Themes/Desktop/Default/Views/TopPanel.xaml, source/Playnite.DesktopApp/ViewModels/DesktopAppViewModel.cs, source/Playnite.DesktopApp/ViewModels/DesktopAppViewModel_Commands.cs, source/Playnite.DesktopApp/Windows/MainWindow.xaml, source/Playnite/Localization/LocSource.xaml, source/Playnite/Localization/LocalizationKeys.cs, source/Playnite/Settings/PlayniteSettings.cs, source/Playnite/ViewModels/RandomGameSelectViewModel.cs
Adds an option to add a button to the TopPanel that selects a random game in the view when activated
https://user-images.githubusercontent.com/1389286/186561646-0b9262d8-d25e-48ab-a414-7d7cc13791c2.mp4
=> Add TopPanel View Random Game Selector button

source/Playnite/ViewModels/MainViewModelBase.cs
- Adds support to display the progress of the installation size scan during library update
=> Display progress during size scan on library update

source/Playnite.DesktopApp/ViewModels/GameEditViewModelFieldChecks.cs
Fixes https://github.com/JosefNemec/Playnite/issues/3078
=> Fix updating install size show data change on "Advanced" tab

source/Playnite/Common/FileSystem.cs
Fix infinite loop on size scan when folder name is whitespace
=> Fix infinite loop on size scan when folder name is whitespace

source/Playnite/Common/FileSystem.cs
=> Fix size on disk scan failing for long paths

source/Playnite/Metadata/MetadataDownloader.cs
=> Skip install size metadata download if game is installed and has value

source/Playnite.DesktopApp/Windows/MetadataComparisonWindow.xaml
Fixes https://github.com/JosefNemec/Playnite/issues/3111
=> Fix CommunityScore radio button not checked in Metadata diff window

source/Playnite.DesktopApp/ViewModels/GameEditViewModelFieldChecks.cs
Fixes https://github.com/JosefNemec/Playnite/issues/3110
=> Fix Updating CompletionStatus shows data change on Advanced tab

source/Playnite/Common/FileSystem.cs, source/Playnite/Common/Paths.cs, source/Playnite/GamesEditor.cs, source/Tests/Playnite.Tests/FileSystemTests.cs
- Fixes general error in long paths with certain number of characters failing (Fixes https://github.com/JosefNemec/Playnite/issues/3107 and https://github.com/JosefNemec/Playnite/issues/3135)
- Fixes Size scan throwing when it game files contains Directory or Files Symlinks that point to targets that don't exist
=> Scan size symlink fixes and longs Path fix

source/Playnite.DesktopApp/ViewModels/DesktopAppViewModel.cs
Only close notifications panel if there isn't any notification when activating an action
Closes https://github.com/JosefNemec/Playnite/issues/3141
=> Only close notifications panel if there isn't any notification when activating an action

README.md
Follow up for https://github.com/JosefNemec/PlayniteExtensions/pull/233, just a name change in the README file.
=> Cleans up Ubisoft Connect naming

source/Playnite.DesktopApp/Controls/Menus/TrayContextMenu.cs, source/Playnite/GamesEditor.cs
=> Add support to show favorite games in tray

source/Playnite/Emulation/Emulators/RosaliesMupenGui/emulator.yaml
=> Add --fullscreen & --quit-after-emulation to RMG

source/Playnite.DesktopApp/Resources/contributors.txt, source/Playnite/GamesEditor.cs
=> Add fullscreen mode to jump list

build/generateRetroArchProfile.ps1, source/Playnite/Emulation/Emulators/Mesen/emulator.yaml, source/Playnite/Emulation/Emulators/RetroArch/emulator.yaml, source/Playnite/Emulation/Emulators/ares/emulator.yaml, source/Playnite/Emulation/Emulators/blueMSX/emulator.yaml, source/Playnite/Emulation/Platforms.yaml
Changes:
- Create "ares" emulator profile ( Closes https://github.com/JosefNemec/Playnite/issues/3282, https://github.com/JosefNemec/Playnite/issues/3022 and https://github.com/JosefNemec/Playnite/issues/2258)
- Create "blueMSX" emulator profile
- Update "Mesen" emulator profile
- Update RetroArch emulator profile (Closes https://github.com/JosefNemec/Playnite/issues/2820)
- Adds some new platforms for emulation
- Creates script to update RetroArch emulator profile
=> Emulation updates

build/generateRetroArchProfile.ps1, source/Playnite/Emulation/Emulators/RetroArch/emulator.yaml, source/Playnite/Emulation/Platforms.yaml
- Fix RetroArch script creating duplicate profiles
- Update RetroArch profile with updated script to fix previously created duplicates
=> Fix RetroArch script creating duplicate profiles

source/Playnite.DesktopApp/Controls/SettingsSections/AppearanceAdvanced.xaml, source/Playnite.DesktopApp/Controls/SettingsSections/AppearanceDetailsView.xaml, source/Playnite.DesktopApp/Controls/Views/GameOverview.cs, source/Playnite.DesktopApp/Themes/Desktop/Default/Views/DetailsViewGameOverview.xaml, source/Playnite.DesktopApp/Themes/Desktop/Default/Views/GridViewGameOverview.xaml, source/Playnite.DesktopApp/ViewModels/GameDetailsViewModel.cs, source/Playnite/Settings/DetailsVisibilitySettings.cs
=> Add support to display game Added Date in game details

source/Playnite.DesktopApp/ViewModels/DatabaseFieldsManagerViewModel.cs, source/Playnite.DesktopApp/Windows/DatabaseFieldsManagerWindow.xaml, source/Playnite/Database/Collections/FilterPresetsCollection.cs, source/Playnite/Database/DatabaseExplorer.cs, source/Playnite/Database/GameDatabase.cs, source/Playnite/Database/InMemoryGameDatabase.cs, source/Playnite/ViewModels/MainViewModelBase.cs, source/Tests/Playnite.Tests/Database/FiltersDatabaseTests.cs, source/Tests/Playnite.Tests/Database/GameDatabaseTests.cs, source/Tests/Playnite.Tests/Playnite.Tests.csproj
Implements:
- Add filter presets to Library Manager
- Support to sort them in a custom order
Partial #2510
Screenshots:
=> Add filter presets to Library Manager. Support for custom sorting.

source/Playnite.DesktopApp/Controls/LibraryStatistics.xaml, source/Playnite.DesktopApp/ViewModels/StatisticsViewModel.cs, source/Playnite/Localization/LocSource.xaml
=> Support to display total install size in statistics view

source/Playnite.DesktopApp/Controls/GamesGridView.xaml, source/Playnite.DesktopApp/Controls/LibraryStatistics.xaml, source/Playnite.DesktopApp/Controls/SettingsSections/AppearanceAdvanced.xaml, source/Playnite.DesktopApp/Controls/Views/GameOverview.cs, source/Playnite.DesktopApp/Windows/GameEditWindow.xaml, source/Playnite/Converters/PlayTimeToStringConverter.cs, source/Playnite/Localization/LocSource.xaml, source/Playnite/Settings/PlayniteSettings.cs, source/Playnite/ViewModels/SearchViewModel.cs, source/Tests/Playnite.Tests/Converters/PlayTimeToStringConverterTests.cs, source/Tests/Playnite.Tests/Playnite.Tests.csproj
Closes https://github.com/JosefNemec/Playnite/issues/3312
Setting is disabled by default
=> Support to indicate number of days played in game time played format

source/Playnite/Emulation/Emulators/Dolphin/emulator.yaml
=> Add m3u format to Nintendo Gamecube profile of Dolphin emulator

source/Playnite.DesktopApp/ViewModels/DatabaseFieldsManagerViewModel.cs
=> Fix filter presets name changes in library manager not saving upon restart

source/Playnite/DateTimes.cs, source/Tests/Playnite.Tests/Extensions/DateTimesTests.cs, source/Tests/Playnite.Tests/Playnite.Tests.csproj
=> Fixed future date display

source/Playnite.DesktopApp/Resources/contributors.txt, source/Playnite/Emulation/Emulators/BizHawk/emulator.yaml, source/Playnite/Emulation/Emulators/melonDS/emulator.yaml, source/Playnite/Emulation/Platforms.yaml
- [✓] These changes work, by building the application and testing them.
- [✓] Pull request is targeting `devel` branch.
- [✓] I added myself into [contributors file](https://github.com/JosefNemec/Playnite/blob/devel/source/Playnite.DesktopApp/Resources/contributors.txt) if I want to receive contribution credit in the application itself.
Update for #3374
=> Update Bizhawk and MelonDS

source/Playnite/Common/Extensions/StringExtensions.cs, source/Playnite/ViewModels/SearchViewModel.cs, source/Tests/Playnite.Tests/Database/GameDatabaseFileTests.cs, source/Tests/Playnite.Tests/Database/GameDatabaseTests.cs, source/Tests/Playnite.Tests/Extensions/StringExtensionTests.cs, source/Tests/Playnite.Tests/Extensions/StringExtensionsTests.cs, source/Tests/Playnite.Tests/ImageSourceManagerTests.cs, source/Tests/Playnite.Tests/Playnite.Tests.csproj, source/Tests/Playnite.Tests/SearchViewModelTests.cs
**Code contributions (pull requests) are currently not being accepted while majority of code base is being rewritten for Playnite 11.**
**Please wait with any pull requests after P11 is at least in beta state.**
Sorry I didn't know that PRs are closed. Opening just in case it could be considered but if there's any issue please feel free to close it :(
---
Closes #3570
Changes:
1. **Improve game results ordering:** Improves game order sorting of keyboard launcher game results to provide more relevant results on top by sorting by [Levenshtein Distance algorithm](https://en.wikipedia.org/wiki/Levenshtein_distance) to provide more relevant results on top. 
2. Subsequently sorts by name and install status (Which is useful if there are duplicates from multiple plugins)
3. **Fuzzy matching:** …
=> Keyboard launcher results improvements

source/Playnite.DesktopApp/Controls/LibraryStatistics.xaml, source/Playnite.DesktopApp/ViewModels/StatisticsViewModel.cs
=> Add GameProvider statistics

source/Playnite.DesktopApp/Controls/Views/ExplorerPanel.cs, source/Playnite.DesktopApp/Themes/Desktop/Default/Views/ExplorerPanel.xaml
Adds Ymir Saturn Emulator Support
=> Add Ymir Saturn Emulator Support
